### ISSUE TITLE
Unused parameters in GUI

### ISSUE THREAD

**Issue by erikfrojdh** [slsdetectorgroup/motorControlSoftware#2]
/home/l_frojdh/software/motorControlSoftware/Gui/src/OptionsWidget.cpp:117:34: warning: unused parameter 'index' [-Wunused-parameter]
void OptionsWidget::SetMotor(int index) {
                                 ^
/home/l_frojdh/software/motorControlSoftware/Gui/src/OptionsWidget.cpp:221:39: warning: unused parameter 'index' [-Wunused-parameter]
void OptionsWidget::SetController(int index) {
                                      ^
/home/l_frojdh/software/motorControlSoftware/Gui/src/OptionsWidget.cpp:298:37: warning: unused parameter 'index' [-Wunused-parameter]
void OptionsWidget::SetRefPoint(int index) {
                                    ^
/home/l_frojdh/software/motorControlSoftware/Gui/src/OptionsWidget.cpp:314:34: warning: unused parameter 'index' [-Wunused-parameter]
void OptionsWidget::SetFluor(int index) {
                                 ^
/home/l_frojdh/software/motorControlSoftware/Gui/src/OptionsWidget.cpp:362:35: warning: unused parameter 'index' [-Wunused-parameter]
void OptionsWidget::SetFwheel(int index)

**Comment by thattil** [comment]
fixed
