### ISSUE TITLE
Unused parameters in the server

### ISSUE THREAD

**Issue by erikfrojdh** [slsdetectorgroup/motorControlSoftware#5]
Adding things here since I'm not sure what can be removed. 

/home/l_frojdh/software/motorControlSoftware/Server/src/Controller.cpp: In static member function ‘static bool Controller::CheckControllerSerialNumber(int, Interface*, std::string)’:
/home/l_frojdh/software/motorControlSoftware/Server/src/Controller.cpp:22:50: warning: unused parameter ‘usbport’ [-Wunused-parameter]
   22 | bool Controller::CheckControllerSerialNumber(int usbport, Interface* interface, std::string serialNumber) {

/home/l_frojdh/software/motorControlSoftware/Server/src/Interface.cpp:702:8: warning: unused variable ‘nextCR’ [-Wunused-variable]
  702 |  char* nextCR = strchr(secondCR + 1,'\r');

gv’ [-Wunused-parameter]
   19 | int main(int argc, char *argv[]) {
      |                    ~~~~~~^~~~~~
/home/l_frojdh/software/motorControlSoftware/Server/src/Server.cpp: In function ‘int main(int, char**)’

Look like this is leftover from some other code? 
```
	int portno = PORT_NO;
	if (argc == 1) {
		FILE_LOG(logINFO) << "Control Server";
	} else {
		FILE_LOG(logINFO) << "Stop Server";
		portno = PORT_NO + 1;
```

**Comment by thattil** [comment]
The first two I fixed. The last one is something I want to try out when I have time. It is to stop the motor. At the moment, all my commands are blocking and not like the way they have described in their handbook. Once I figure that out, all of this will come into effect, including stop Motor that you might see in some places that are commented out. For now, you can leave it.
